url: https://marcosrochedo.github.io
baseurl: /marcosrochedo.github.io/

# Site settings
title: Marcos Rocha
email: marcos.paulo.rocha@usp.br
description: Escrever aqui uma descrição impressionante!!!

# Team names, titles and social links
people:

- name: Marcos Rocha
  pic: 2
  position: Engenheiro Agrônomo
  social:
    - title: instagram
      url: https://www.instagram.com/marcosrochedo/
    - title: facebook
      url: https://www.facebook.com/mpar23
    - title: linkedin
      url: https://www.linkedin.com/in/marcos-rocha-2b5a45141/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: kaggle 
    url: https://www.kaggle.com/marcosrocha23
  - title: github
    url: http://github.com/marcosrochedo

# Postal address (add as many lines as necessary)
address:
  - line: Av. Pádua Dias - Agronomia
  - line: Piracicaba, SP - Brasil

# Build settings
markdown: kramdown
permalink: pretty
